version: "3"
services:
  server:
    build:
      context: ./server/
    ports:
      - "5000:5000"
  client:
    build:
      context: ./client/
    depends_on:
      - server
    links:
      - "server"
    ports:
      - "3000:80"
